### ISSUE TITLE
go_package option has a trailing slash

### ISSUE THREAD

**Issue by chongkai** [cloudstateio/go-support#29]
Hi @marcellanz,

In file, https://github.com/cloudstateio/go-support/blob/master/protobuf/frontend/cloudstate/entity_key.proto, the go_package option has a tailing slash, 
`option go_package = "github.com/cloudstateio/go-support/cloudstate/;cloudstate";`
 which causes the following import in the generated go code,
`_ "github.com/cloudstateio/go-support/cloudstate/"`
go compile reports error "non-canonical import path" on such code.

**Comment by marcellanz** [comment]
Hi @chongkai thank you for reporting.

This issue is fixed for the next milestone:
https://github.com/cloudstateio/go-support/commit/717ea954adde602bcd5c138b11e46df52b933aad#diff-f4fa7a5e1066ffb884d50658351c83f0

Other issue was found with non-absolute paths having multiple path elements for the Go package in proto files, that is not an issue when protoc used with matching directory structure but other tools (CUE,..)

**Comment by marcellanz** [comment]
fixed for v0.2.0
