### ISSUE TITLE
 non-canonical import path "github.com/cloudstateio/go-support/cloudstate/" (should be "github.com/cloudstateio/go-support/cloudstate")

### ISSUE THREAD

**Issue by edwardcallahan** [cloudstateio/go-support#37]
Compiling the shopping cart example results in an error when compiling `shoppingcart.pb.go`
The import:
`	_ "github.com/cloudstateio/go-support/cloudstate/"`
results in:
`shopping/shoppingcart.pb.go:16:2: non-canonical import path "github.com/cloudstateio/go-support/cloudstate/" (should be "github.com/cloudstateio/go-support/cloudstate")`
expected: no error

This can be addressed by removing the trailing `/` from
[entity_key.proto](https://github.com/cloudstateio/go-support/blob/master/protobuf/frontend/cloudstate/entity_key.proto#L26) as in:
`option go_package = "github.com/cloudstateio/go-support/cloudstate;cloudstate";`

**Comment by sleipnir** [comment]
I think this is mapped in another issue. I will check if it is a duplicate

**Comment by sleipnir** [comment]
I think it was solved in version 0.2.0 https://github.com/cloudstateio/go-support/issues/29

**Comment by marcellanz** [comment]
@edwardcallahan thanks for reporting this! As @sleipnir mentioned this is a known issue and milestone v0.2.0 is (very) soon to be released where this issue is fixed. A few things will change also API wise with the Go support with this release

The CRDT branch has all the new things coming:
https://github.com/cloudstateio/go-support/tree/feature/crdt_support

**Comment by edwardcallahan** [comment]
Thank you @marcellanz, and @sleipnir.
